import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { eventSeeds } from '../src/game-data/events.js';
import { loadLegacy } from './legacy-loader.js';

interface LegacyEvent {
  scenes?: Record<string, unknown>;
}

const slug = (value: string): string => value
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/^-|-$/g, '');

const scenes = eventSeeds.flatMap(([eventId, legacyRef, sourceFile]) => {
  const event = loadLegacy<LegacyEvent>(sourceFile, legacyRef);
  return Object.keys(event.scenes ?? {}).map((legacyKey) => ({
    id: `scene.${eventId.slice('event.'.length)}.${slug(legacyKey)}`,
    eventId,
    legacyKey,
    sourceFile,
  }));
});

const output = `import type { SceneMetadata } from '../schema.js';\n\n` +
  `// Generated by tools/generate-event-scenes.ts. Do not edit by hand.\n` +
  `export const scenes = ${JSON.stringify(scenes, null, 2)} satisfies SceneMetadata[];\n`;

writeFileSync(resolve(process.cwd(), 'src/game-data/generated/scenes.ts'), output);
console.log(`Generated ${scenes.length} stable scene IDs.`);
