import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { eventSeeds } from '../src/game-data/events.js';
import { resources } from '../src/game-data/resources.js';
import { blueprints, items } from '../src/game-data/items.js';
import { loadLegacy } from './legacy-loader.js';

interface LegacyRoll {
  min: number;
  max: number;
  chance: number;
  bonus?: LegacyRoll;
}

interface LegacyScene {
  combat?: boolean;
  enemy?: string;
  damage?: number;
  hit?: number;
  attackDelay?: number;
  health?: number;
  ranged?: boolean;
  loot?: Record<string, LegacyRoll>;
}

interface LegacyEvent { scenes?: Record<string, LegacyScene> }

const slug = (value: string): string => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const idByLegacyKey = new Map(
  [...resources, ...items, ...blueprints].map(({ id, legacyKey }) => [legacyKey, id]),
);

const targetId = (legacyKey: string): string => {
  if (legacyKey.endsWith(' blueprint')) {
    const blueprint = idByLegacyKey.get(legacyKey.slice(0, -' blueprint'.length));
    if (blueprint?.startsWith('blueprint.')) return blueprint;
  }
  const id = idByLegacyKey.get(legacyKey);
  if (!id) throw new Error(`Unknown loot target: ${legacyKey}`);
  return id;
};

const enemiesByKey = new Map<string, { id: string; legacyKey: string; sourceFile: string }>();
const combatEncounters: object[] = [];
const lootTables: object[] = [];

for (const [eventId, legacyRef, sourceFile] of eventSeeds) {
  const event = loadLegacy<LegacyEvent>(sourceFile, legacyRef);
  for (const [sceneKey, scene] of Object.entries(event.scenes ?? {})) {
    const suffix = `${eventId.slice('event.'.length)}.${slug(sceneKey)}`;
    const sceneId = `scene.${suffix}`;
    if (scene.combat) {
      if (!scene.enemy || scene.damage === undefined || scene.hit === undefined || scene.attackDelay === undefined || scene.health === undefined) {
        throw new Error(`Incomplete combat data at ${eventId}/${sceneKey}`);
      }
      const enemyId = `enemy.${slug(scene.enemy)}`;
      enemiesByKey.set(scene.enemy, { id: enemyId, legacyKey: scene.enemy, sourceFile });
      combatEncounters.push({
        id: `encounter.${suffix}`,
        eventId,
        sceneId,
        enemyId,
        legacyKey: sceneKey,
        sourceFile,
        damage: scene.damage,
        hitChance: scene.hit,
        attackDelaySeconds: scene.attackDelay,
        health: scene.health,
        ranged: scene.ranged ?? false,
      });
    }
    if (scene.loot) {
      lootTables.push({
        id: `loot.${suffix}`,
        eventId,
        sceneId,
        legacyKey: sceneKey,
        sourceFile,
        entries: Object.entries(scene.loot).map(([legacyKey, roll]) => ({
          targetId: targetId(legacyKey),
          min: roll.min,
          maxExclusive: roll.max,
          chance: roll.chance,
          ...(roll.bonus ? { bonus: { min: roll.bonus.min, maxExclusive: roll.bonus.max, chance: roll.bonus.chance } } : {}),
        })),
      });
    }
  }
}

const enemies = [...enemiesByKey.values()].sort((a, b) => a.id.localeCompare(b.id));
const output = `import type { CombatEncounterDefinition, EnemyDefinition, LootTableDefinition } from '../schema.js';\n\n` +
  `// Generated by tools/generate-combat-catalog.ts. Do not edit by hand.\n` +
  `export const enemies = ${JSON.stringify(enemies, null, 2)} satisfies EnemyDefinition[];\n\n` +
  `export const combatEncounters = ${JSON.stringify(combatEncounters, null, 2)} satisfies CombatEncounterDefinition[];\n\n` +
  `export const lootTables = ${JSON.stringify(lootTables, null, 2)} satisfies LootTableDefinition[];\n`;

writeFileSync(resolve(process.cwd(), 'src/game-data/generated/combat.ts'), output);
console.log(`Generated ${enemies.length} enemies, ${combatEncounters.length} combat encounters, and ${lootTables.length} loot tables.`);
