import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { baseline } from '../src/game-data/index.js';
import { lightRoomOverlay } from '../src/light-room/overlay.js';

const legacyKeyById = new Map(
  [...baseline.resources, ...baseline.buildings].map(({ id, legacyKey }) => [id, legacyKey]),
);
const professionKeyById = new Map(
  baseline.professions.map(({ id, legacyKey }) => [id, legacyKey]),
);
const professionRuntimeKey = (id: string) => {
  const key = professionKeyById.get(id);
  if (!key) throw new Error(`No legacy profession runtime key for ${id}`);
  return key;
};

const legacyAmounts = (amounts: Record<string, number>) => Object.fromEntries(
  Object.entries(amounts).map(([id, value]) => {
    const legacyKey = legacyKeyById.get(id);
    if (!legacyKey) throw new Error(`No legacy runtime key for ${id}`);
    return [legacyKey, value];
  }),
);

const runtimeData = {
  version: lightRoomOverlay.version,
  buildings: lightRoomOverlay.buildings.map((building) => ({
    key: building.runtimeKey,
    name: building.name,
    maximum: building.maximum,
    cost: legacyAmounts(building.cost.amounts),
    requiresBuilding: building.unlockWhen.kind === 'has-building'
      ? legacyKeyById.get(building.unlockWhen.buildingId)
      : undefined,
    availableMessage: building.availableMessage,
    builtMessage: building.builtMessage,
  })),
  professions: lightRoomOverlay.professions.map((profession) => ({
    key: profession.runtimeKey,
    name: profession.name,
    requiresBuilding: lightRoomOverlay.buildings
      .find(({ id }) => id === profession.requiresBuildingId)?.runtimeKey,
    maximum: profession.maximumWorkers,
    delay: profession.intervalSeconds,
    stores: legacyAmounts(profession.flows),
    modifiers: profession.modifiers.map((modifier) => ({
      upgrade: modifier.when.kind === 'has-upgrade'
        ? lightRoomOverlay.upgrades.find(({ id }) => id === modifier.when.upgradeId)?.runtimeKey
        : undefined,
      stores: legacyAmounts(modifier.flows),
    })),
  })),
  professionPatches: lightRoomOverlay.professionPatches.map((patch) => ({
    key: professionRuntimeKey(patch.targetProfessionId),
    delay: patch.intervalSeconds,
    randomFinds: patch.randomFinds.map((find) => ({
      store: legacyKeyById.get(find.resourceId),
      chance: find.chance,
      amount: find.amount,
    })),
  })),
  upgrades: lightRoomOverlay.upgrades.map((upgrade) => ({
    key: upgrade.runtimeKey,
    name: upgrade.name,
    acquisitionStatus: upgrade.acquisitionStatus,
  })),
};

const output = `// Generated by tools/generate-light-room-runtime.ts. Do not edit by hand.\n` +
  `var LightRoomData = ${JSON.stringify(runtimeData, null, 2)};\n`;

const generatedDirectory = resolve(process.cwd(), 'script/generated');
mkdirSync(generatedDirectory, { recursive: true });
writeFileSync(resolve(generatedDirectory, 'light_room_content.js'), output);
console.log(`Generated ${runtimeData.buildings.length} Light Room buildings and ${runtimeData.professions.length} professions.`);
